name: Deploy Spring Boot Application

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: mvn clean install

    - name: Run tests
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: mvn test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: spring-boot-app
        path: target/*.jar
